project:
  type: website

website:
  title: "Code Gone Wild"
  navbar:
    logo: "img/logo.png"
    background: secondary
    tools:
      - icon: github
        href: https://github.com/checkdgt
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: My Work

format:
  html:
    theme:
      light: vapor
      dark: darkly
    css: styles.css
    toc: true
